version: '3.8'

services:
  postgres-db:
    image: postgres:12.0-alpine
    restart: always
    environment:
        POSTGRES_DB: discord_bot_bex
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
    ports:
        - "5432:5432"
